#!/usr/bin/env python3
"""
assemble-spawn-package.py — CLI entry point for the spawn package assembler.

Usage:
    python3 assemble-spawn-package.py \\
        --plan spawn-plan.json \\
        --state bootstrap-state.json \\
        [--output-dir /opt/broodforge/spawn-packages] \\
        [--kdbx /path/to/cell.kdbx] \\
        [--artifacts /path/to/pre-generated-artifacts/]

If --artifacts is omitted, all phase scripts and IaC are generated from the
spawn plan automatically. This is the normal operator workflow.

Produces:
    spawn-package-{cell_id}-{hostname}-{timestamp}.tar.gz
"""

import argparse
import json
import sys
from pathlib import Path

_HERE = Path(__file__).parent
sys.path.insert(0, str(_HERE))

from assemble_spawn_package import assemble_spawn_package


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Assemble a spawn package for broodling provisioning",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--plan", required=True,
        help="Path to spawn-plan.json (generated by spawn-planner.py)",
    )
    parser.add_argument(
        "--state", "--manifest", dest="state", default="bootstrap-state.json",
        help="Path to bootstrap-state.json / spawn-manifest.json "
             "(default: bootstrap-state.json)",
    )
    parser.add_argument(
        "--artifacts", default=None,
        help="Directory containing pre-generated artifacts (phase scripts, opentofu/, etc.). "
             "If omitted, all scripts are generated automatically from the plan.",
    )
    parser.add_argument(
        "--output-dir", default=".",
        help="Directory to write the package into (default: current directory)",
    )
    parser.add_argument(
        "--kdbx", default=None,
        help="Path to KeePass .kdbx to embed in the package (optional)",
    )
    args = parser.parse_args()

    plan_path = Path(args.plan)
    state_path = Path(args.state)

    for label, p in [("Plan", plan_path), ("State", state_path)]:
        if not p.exists():
            print(f"[error] {label} not found: {p}", file=sys.stderr)
            sys.exit(1)

    artifacts_dir = Path(args.artifacts) if args.artifacts else None
    if artifacts_dir is not None and not artifacts_dir.exists():
        print(f"[error] Artifacts directory not found: {artifacts_dir}", file=sys.stderr)
        sys.exit(1)

    with open(plan_path) as f:
        plan = json.load(f)
    with open(state_path) as f:
        raw_state = json.load(f)

    # Convert bootstrap-state.json to a proper spawn manifest (adds hatchery_url,
    # receiver_token, reserved VMIDs/IPs, etc.) if the state file is a bootstrap-state
    # (identified by the absence of "schema_version" with value "spawn-manifest-*").
    manifest = raw_state
    try:
        from hatchery_state import read_hatchery_state
        spawn_manifest_version = raw_state.get("schema_version", "")
        if not str(spawn_manifest_version).startswith("spawn-manifest"):
            manifest = read_hatchery_state(raw_state).raw
    except ImportError:
        pass  # hatchery_state not available; use raw state as-is

    kdbx_path = Path(args.kdbx) if args.kdbx else None
    if kdbx_path and not kdbx_path.exists():
        print(f"[error] KeePass database not found: {kdbx_path}", file=sys.stderr)
        sys.exit(1)

    pkg = assemble_spawn_package(
        plan=plan,
        manifest=manifest,
        artifacts_dir=artifacts_dir,
        output_dir=Path(args.output_dir),
        kdbx_path=kdbx_path,
    )

    cell_id  = plan.get("cell_id", "unknown")
    hostname = plan.get("hostname", "unknown")
    mode     = (plan.get("disposition") or {}).get("execution_mode", "unknown")

    print(f"\n{'=' * 64}")
    print(f"  Spawn Package Assembled")
    print(f"{'=' * 64}")
    print(f"  Package:  {pkg}")
    print(f"  Cell:     {cell_id}")
    print(f"  Broodling:{hostname}")
    print(f"  Mode:     {mode}")
    print(f"\n  Next steps:")
    print(f"    1. Copy {pkg.name} to {hostname}")
    print(f"    2. Extract: tar -xzf {pkg.name}")
    print(f"    3. Run:     bash spawn.sh")
    print()


if __name__ == "__main__":
    main()
