"""
generate_talos_config.py — Talos machine config generator (stdlib only)

Reads k3s-cluster.yaml and bootstrap-state.json to generate declarative Talos
machine configs for each node declared with os_variant: talos.

Output: talos-configs/
  controlplane.yaml      — base control-plane machine config
  worker.yaml            — base worker machine config
  patches/<vm_name>.yaml — per-node IP/hostname patches
  installer-template.yaml — minimal config for template build (no cluster join)
  talosconfig            — operator client config (fill endpoint/CA after genconfig)

Usage:
  python3 proxmox-bootstrap/generate_talos_config.py \\
      --state  proxmox-bootstrap/bootstrap-state.json \\
      --k3s    proxmox-bootstrap/metadata/k3s-cluster.yaml \\
      --output talos-configs/

  python3 proxmox-bootstrap/generate_talos_config.py --help

Design notes:
  - All output is plain YAML; no external deps required.
  - Cluster secret (token, CA) must be generated by talosctl genconfig first;
    this tool generates the structural/network patches that override those secrets.
  - If talosctl is available, --genconfig flag calls it and merges output.
  - Nodes with os_variant != 'talos' are silently skipped.
  - An installer-template.yaml is always generated for use by build-talos-template.sh.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import dataclass, field
from typing import Optional

# ── YAML emit (stdlib only) ────────────────────────────────────────────────────
# We only need a small subset of YAML; implement a minimal emitter.

def _yaml_str(v: str) -> str:
    """Quote a string value if it contains special YAML characters."""
    need_quote = any(c in v for c in (':', '#', '[', ']', '{', '}', ',', '&', '*', '?', '|', '<', '>', '=', '!', '%', '@', '`', "'", '"', '\n'))
    if need_quote:
        escaped = v.replace('\\', '\\\\').replace('"', '\\"')
        return f'"{escaped}"'
    return v


def _yaml_val(v) -> str:
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return _yaml_str(str(v))


def _emit_yaml(obj, indent: int = 0) -> str:
    pad = "  " * indent
    if isinstance(obj, dict):
        lines = []
        for k, v in obj.items():
            if isinstance(v, (dict, list)):
                lines.append(f"{pad}{k}:")
                lines.append(_emit_yaml(v, indent + 1))
            else:
                lines.append(f"{pad}{k}: {_yaml_val(v)}")
        return "\n".join(lines)
    if isinstance(obj, list):
        if not obj:
            return f"{pad}[]"
        lines = []
        for item in obj:
            if isinstance(item, (dict, list)):
                first_line, *rest_lines = _emit_yaml(item, indent + 1).splitlines()
                lines.append(f"{pad}- {first_line.lstrip()}")
                for rl in rest_lines:
                    lines.append(rl)
            else:
                lines.append(f"{pad}- {_yaml_val(item)}")
        return "\n".join(lines)
    return f"{pad}{_yaml_val(obj)}"


# ── Data structures ────────────────────────────────────────────────────────────

@dataclass
class TalosNodeSpec:
    vm_name: str
    role: str               # "controlplane" | "worker"
    hostname: str
    ip: str
    gateway: str
    nameserver: str
    install_disk: str = "/dev/sda"
    os_variant: str = "talos"


@dataclass
class TalosClusterSpec:
    cluster_name: str
    cluster_endpoint: str   # https://<control-plane-ip>:6443
    nodes: list[TalosNodeSpec] = field(default_factory=list)
    k3s_version: Optional[str] = None


# ── Loaders ────────────────────────────────────────────────────────────────────

def _load_yaml_simple(path: str) -> dict:
    """Minimal YAML loader for the project's config files (stdlib only).

    Handles nested mappings, sequences, comments, and quoted strings.
    Not a full YAML parser — sufficient for k3s-cluster.yaml and bootstrap-state.json.
    """
    try:
        import yaml  # type: ignore
        with open(path) as f:
            return yaml.safe_load(f) or {}
    except ImportError:
        pass

    # Fallback: line-by-line parser for simple YAML
    with open(path) as f:
        lines = f.readlines()

    def _parse(lines: list[str], base_indent: int = 0) -> dict | list | str | None:
        result: dict | list | None = None
        i = 0
        while i < len(lines):
            raw = lines[i]
            stripped = raw.rstrip()
            if not stripped or stripped.lstrip().startswith('#'):
                i += 1
                continue
            indent = len(raw) - len(raw.lstrip())
            if indent < base_indent:
                break
            content = stripped.strip()
            if content.startswith('- '):
                if result is None:
                    result = []
                assert isinstance(result, list)
                val = content[2:].strip()
                if ':' in val:
                    sub = {val.split(':', 1)[0].strip(): val.split(':', 1)[1].strip() or None}
                    result.append(sub)
                else:
                    result.append(_clean_val(val))
            elif ':' in content:
                if result is None:
                    result = {}
                assert isinstance(result, dict)
                k, _, v = content.partition(':')
                k = k.strip()
                v = v.strip()
                # Comment strip
                if ' #' in v:
                    v = v[:v.index(' #')].strip()
                if v == '':
                    # Block value follows
                    child_lines = []
                    j = i + 1
                    while j < len(lines):
                        child_raw = lines[j]
                        child_stripped = child_raw.rstrip()
                        if not child_stripped or child_stripped.lstrip().startswith('#'):
                            j += 1
                            child_lines.append(child_raw)
                            continue
                        child_indent = len(child_raw) - len(child_raw.lstrip())
                        if child_indent <= indent:
                            break
                        child_lines.append(child_raw)
                        j += 1
                    result[k] = _parse(child_lines, indent + 1)
                    i = j
                    continue
                else:
                    result[k] = _clean_val(v)
            i += 1
        return result

    def _clean_val(v: str):
        if v in ('true', 'True'):
            return True
        if v in ('false', 'False'):
            return False
        if v in ('null', 'Null', 'None', '~', ''):
            return None
        try:
            return int(v)
        except ValueError:
            pass
        try:
            return float(v)
        except ValueError:
            pass
        # Strip quotes
        if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
            return v[1:-1]
        return v

    return _parse(lines) or {}


def _find_vm_ip(state: dict, vm_name: str) -> str:
    """Look up VM IP from dns_registry or vms list."""
    for entry in state.get("dns_registry", []):
        if entry.get("hostname") == vm_name or entry.get("name") == vm_name:
            return entry.get("ip", "POPULATE")
    for vm in state.get("vms", []):
        if vm.get("name") == vm_name:
            return vm.get("ip", "POPULATE")
    return "POPULATE"


def _gateway(state: dict) -> str:
    topo = state.get("network_topology_declared", {}) or state.get("network_topology", {})
    return (topo.get("gateway") or
            state.get("host_identity", {}).get("gateway") or
            "POPULATE")


def _nameserver(state: dict) -> str:
    hi = state.get("host_identity", {}) or {}
    topo = state.get("network_topology_declared", {}) or {}
    return (hi.get("nameserver") or
            topo.get("dns_servers", [None])[0] if topo.get("dns_servers") else None or
            hi.get("lan_ip") or
            "POPULATE")


def build_cluster_spec(k3s: dict, state: dict) -> TalosClusterSpec:
    """Build a TalosClusterSpec from k3s-cluster.yaml and bootstrap-state.json."""
    cluster_name = k3s.get("cluster_name", "homelab-k3s")
    hi = state.get("host_identity", {}) or {}
    gateway = _gateway(state)
    nameserver = _nameserver(state)

    nodes: list[TalosNodeSpec] = []

    for node in k3s.get("server_nodes", []) or []:
        if node.get("os_variant", "ubuntu") != "talos":
            continue
        vm_name = node.get("vm_name", "k3s-server-01")
        ip = _find_vm_ip(state, vm_name)
        nodes.append(TalosNodeSpec(
            vm_name=vm_name,
            role="controlplane",
            hostname=vm_name,
            ip=ip,
            gateway=gateway,
            nameserver=nameserver,
        ))

    for node in k3s.get("worker_nodes", []) or []:
        if node.get("os_variant", "ubuntu") != "talos":
            continue
        vm_name = node.get("vm_name", "k3s-worker-01")
        ip = _find_vm_ip(state, vm_name)
        nodes.append(TalosNodeSpec(
            vm_name=vm_name,
            role="worker",
            hostname=vm_name,
            ip=ip,
            gateway=gateway,
            nameserver=nameserver,
        ))

    # Cluster endpoint = first control-plane node IP
    cp_nodes = [n for n in nodes if n.role == "controlplane"]
    if cp_nodes and cp_nodes[0].ip != "POPULATE":
        endpoint = f"https://{cp_nodes[0].ip}:6443"
    else:
        endpoint = "https://POPULATE:6443"

    k3s_version = k3s.get("kubernetes_version", None)
    if isinstance(k3s_version, str) and k3s_version.startswith("POPULATE"):
        k3s_version = None

    return TalosClusterSpec(
        cluster_name=cluster_name,
        cluster_endpoint=endpoint,
        nodes=nodes,
        k3s_version=k3s_version,
    )


# ── Config generators ──────────────────────────────────────────────────────────

def generate_installer_template(output_dir: str) -> None:
    """9.T.2 companion — minimal Talos config for template build.

    Used by build-talos-template.sh to boot into installer mode.
    The VM installs Talos to disk and halts; no cluster is joined.
    """
    config = {
        "version": "v1alpha1",
        "debug": False,
        "persist": False,
        "machine": {
            "type": "worker",
            "token": "INSTALLER_ONLY_NOT_FOR_CLUSTER_USE",
            "install": {
                "disk": "/dev/sda",
                "bootloader": True,
                "wipe": True,
            },
            "network": {
                "hostname": "talos-template-builder",
            },
            "features": {
                "rbac": False,
            },
        },
        "cluster": {
            "id": "INSTALLER_ONLY",
            "secret": "INSTALLER_ONLY",
            "controlPlane": {
                "endpoint": "https://127.0.0.1:6443",
            },
            "clusterName": "template-build",
            "network": {
                "podSubnets": ["10.244.0.0/16"],
                "serviceSubnets": ["10.96.0.0/12"],
            },
            "token": "INSTALLER_ONLY",
            "secretboxEncryptionSecret": "INSTALLER_ONLY",
            "ca": {
                "crt": "INSTALLER_ONLY",
                "key": "INSTALLER_ONLY",
            },
            "aggregatorCA": {
                "crt": "INSTALLER_ONLY",
                "key": "INSTALLER_ONLY",
            },
            "serviceAccount": {
                "key": "INSTALLER_ONLY",
            },
        },
    }
    path = os.path.join(output_dir, "installer-template.yaml")
    with open(path, "w") as f:
        f.write("# Talos installer-template.yaml\n")
        f.write("# Used by build-talos-template.sh — boots into installer mode only.\n")
        f.write("# Do NOT use for actual cluster nodes.\n")
        f.write("# After template creation, generate real configs with:\n")
        f.write("#   talosctl gen config <cluster-name> <endpoint>\n")
        f.write("#   python3 proxmox-bootstrap/generate-talos-config.py ...\n\n")
        f.write(_emit_yaml(config))
        f.write("\n")
    print(f"[talos-config] Written: {path}")


def generate_node_patch(node: TalosNodeSpec, output_dir: str) -> None:
    """Generate a per-node strategic merge patch for network and hostname."""
    patch: dict = {
        "machine": {
            "network": {
                "hostname": node.hostname,
                "interfaces": [
                    {
                        "interface": "eth0",
                        "addresses": [f"{node.ip}/24"],
                        "routes": [
                            {
                                "network": "0.0.0.0/0",
                                "gateway": node.gateway,
                            }
                        ],
                        "dhcp": False,
                    }
                ],
                "nameservers": [node.nameserver],
            }
        }
    }

    patches_dir = os.path.join(output_dir, "patches")
    os.makedirs(patches_dir, exist_ok=True)
    path = os.path.join(patches_dir, f"{node.vm_name}.yaml")
    with open(path, "w") as f:
        f.write(f"# Per-node patch for {node.vm_name} ({node.role})\n")
        f.write(f"# Apply with: talosctl apply-config --nodes {node.ip} \\\n")
        f.write(f"#   --file {node.role}.yaml --patch @patches/{node.vm_name}.yaml\n\n")
        f.write(_emit_yaml(patch))
        f.write("\n")
    print(f"[talos-config] Written: {path}")


def generate_base_controlplane(spec: TalosClusterSpec, output_dir: str) -> None:
    """Generate the base controlplane.yaml (secrets = POPULATE; use talosctl genconfig)."""
    config = {
        "version": "v1alpha1",
        "debug": False,
        "persist": True,
        "machine": {
            "type": "controlplane",
            "token": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            "ca": {
                "crt": "POPULATE_FROM_TALOSCTL_GENCONFIG",
                "key": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            },
            "certSANs": [],
            "install": {
                "disk": "/dev/sda",
                "bootloader": True,
                "wipe": False,
            },
            "network": {
                "nameservers": ["POPULATE_FROM_PATCH"],
            },
            "time": {
                "servers": ["time.cloudflare.com"],
            },
            "features": {
                "rbac": True,
            },
        },
        "cluster": {
            "id": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            "secret": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            "controlPlane": {
                "endpoint": spec.cluster_endpoint,
            },
            "clusterName": spec.cluster_name,
            "network": {
                "cni": {
                    "name": "none",
                },
                "podSubnets": ["10.42.0.0/16"],
                "serviceSubnets": ["10.43.0.0/16"],
            },
            "token": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            "secretboxEncryptionSecret": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            "ca": {
                "crt": "POPULATE_FROM_TALOSCTL_GENCONFIG",
                "key": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            },
            "aggregatorCA": {
                "crt": "POPULATE_FROM_TALOSCTL_GENCONFIG",
                "key": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            },
            "serviceAccount": {
                "key": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            },
            "apiServer": {
                "certSANs": [],
                "disablePodSecurityPolicy": True,
            },
            "etcd": {
                "ca": {
                    "crt": "POPULATE_FROM_TALOSCTL_GENCONFIG",
                    "key": "POPULATE_FROM_TALOSCTL_GENCONFIG",
                }
            },
            "coreDNS": {
                "disabled": False,
            },
        },
    }

    path = os.path.join(output_dir, "controlplane.yaml")
    with open(path, "w") as f:
        f.write(f"# Talos controlplane.yaml — cluster: {spec.cluster_name}\n")
        f.write("# IMPORTANT: POPULATE_FROM_TALOSCTL_GENCONFIG fields must be filled\n")
        f.write("#   by running: talosctl gen config <cluster-name> <endpoint>\n")
        f.write("# Then apply per-node patches from patches/<vm_name>.yaml\n\n")
        f.write(_emit_yaml(config))
        f.write("\n")
    print(f"[talos-config] Written: {path}")


def generate_base_worker(spec: TalosClusterSpec, output_dir: str) -> None:
    """Generate the base worker.yaml (secrets = POPULATE; use talosctl genconfig)."""
    config = {
        "version": "v1alpha1",
        "debug": False,
        "persist": True,
        "machine": {
            "type": "worker",
            "token": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            "ca": {
                "crt": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            },
            "install": {
                "disk": "/dev/sda",
                "bootloader": True,
                "wipe": False,
            },
            "network": {
                "nameservers": ["POPULATE_FROM_PATCH"],
            },
            "time": {
                "servers": ["time.cloudflare.com"],
            },
        },
        "cluster": {
            "id": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            "secret": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            "controlPlane": {
                "endpoint": spec.cluster_endpoint,
            },
            "clusterName": spec.cluster_name,
            "token": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            "ca": {
                "crt": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            },
            "network": {
                "podSubnets": ["10.42.0.0/16"],
                "serviceSubnets": ["10.43.0.0/16"],
            },
        },
    }

    path = os.path.join(output_dir, "worker.yaml")
    with open(path, "w") as f:
        f.write(f"# Talos worker.yaml — cluster: {spec.cluster_name}\n")
        f.write("# IMPORTANT: POPULATE_FROM_TALOSCTL_GENCONFIG fields must be filled\n")
        f.write("#   by running: talosctl gen config <cluster-name> <endpoint>\n\n")
        f.write(_emit_yaml(config))
        f.write("\n")
    print(f"[talos-config] Written: {path}")


def generate_talosconfig_stub(spec: TalosClusterSpec, output_dir: str) -> None:
    """Generate a talosconfig stub; CA and nodes filled by talosctl genconfig."""
    cp_nodes = [n for n in spec.nodes if n.role == "controlplane"]
    endpoints = [n.ip for n in cp_nodes if n.ip != "POPULATE"] or ["POPULATE"]
    nodes = [n.ip for n in spec.nodes if n.ip != "POPULATE"] or ["POPULATE"]

    config = {
        "context": spec.cluster_name,
        "contexts": {
            spec.cluster_name: {
                "endpoints": endpoints,
                "nodes": nodes,
                "ca": "POPULATE_FROM_TALOSCTL_GENCONFIG",
                "crt": "POPULATE_FROM_TALOSCTL_GENCONFIG",
                "key": "POPULATE_FROM_TALOSCTL_GENCONFIG",
            }
        },
    }

    path = os.path.join(output_dir, "talosconfig")
    with open(path, "w") as f:
        f.write(f"# talosconfig — operator client config for cluster: {spec.cluster_name}\n")
        f.write("# CA, crt, and key are filled by: talosctl gen config <name> <endpoint>\n\n")
        f.write(_emit_yaml(config))
        f.write("\n")
    print(f"[talos-config] Written: {path}")


def run_talosctl_genconfig(spec: TalosClusterSpec, output_dir: str) -> bool:
    """Optionally call talosctl to generate secrets and merge with our structural configs."""
    if not spec.nodes:
        return False
    try:
        result = subprocess.run(
            ["talosctl", "gen", "config", spec.cluster_name, spec.cluster_endpoint,
             "--output-dir", output_dir, "--output-types", "controlplane,worker,talosconfig",
             "--force"],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            print("[talos-config] talosctl genconfig succeeded — secrets embedded in config files")
            return True
        else:
            print(f"[talos-config] talosctl genconfig failed: {result.stderr.strip()}")
            return False
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def write_readme(spec: TalosClusterSpec, output_dir: str, used_talosctl: bool) -> None:
    lines = [
        f"# Talos Machine Configs — {spec.cluster_name}",
        "",
        "Generated by `generate-talos-config.py`.",
        "",
        "## Files",
        "",
        "| File | Purpose |",
        "|---|---|",
        "| `controlplane.yaml` | Base control-plane machine config |",
        "| `worker.yaml` | Base worker machine config |",
        "| `patches/<vm>.yaml` | Per-node IP/hostname patch |",
        "| `installer-template.yaml` | Minimal config for Proxmox template build |",
        "| `talosconfig` | Operator client config (talosctl) |",
        "",
    ]

    if used_talosctl:
        lines += [
            "## Status",
            "",
            "Secrets were generated by `talosctl genconfig`. The config files are ready to apply.",
            "",
            "## Apply per-node configs",
            "",
            "```",
        ]
        for node in spec.nodes:
            lines.append(
                f"talosctl apply-config --insecure --nodes {node.ip} "
                f"--file {node.role}.yaml "
                f"--patch @patches/{node.vm_name}.yaml"
            )
        lines += ["```", ""]
    else:
        lines += [
            "## Next steps",
            "",
            "1. Install `talosctl` (see docs/TALOS-ALTERNATIVE.md for install command).",
            "2. Generate cluster secrets:",
            "",
            f"   ```",
            f"   talosctl gen config {spec.cluster_name} {spec.cluster_endpoint} \\",
            f"     --output-dir talos-configs/ \\",
            f"     --output-types controlplane,worker,talosconfig \\",
            f"     --force",
            f"   ```",
            "",
            "3. Apply per-node patches (run from hatchery):",
            "",
            "   ```",
        ]
        for node in spec.nodes:
            lines.append(
                f"   talosctl apply-config --insecure --nodes {node.ip} "
                f"--file {node.role}.yaml "
                f"--patch @patches/{node.vm_name}.yaml"
            )
        lines += ["   ```", ""]

    if spec.nodes:
        lines += [
            "## Nodes declared with os_variant: talos",
            "",
            "| VM | Role | IP |",
            "|---|---|---|",
        ]
        for node in spec.nodes:
            lines.append(f"| {node.vm_name} | {node.role} | {node.ip} |")
        lines.append("")

    path = os.path.join(output_dir, "README.md")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print(f"[talos-config] Written: {path}")


# ── Main ───────────────────────────────────────────────────────────────────────

def generate_talos_configs(
    state_path: str,
    k3s_path: str,
    output_dir: str,
    genconfig: bool = False,
) -> TalosClusterSpec:
    """Full config generation pipeline. Returns the cluster spec."""
    state = json.load(open(state_path)) if os.path.exists(state_path) else {}
    k3s = _load_yaml_simple(k3s_path) if os.path.exists(k3s_path) else {}

    spec = build_cluster_spec(k3s, state)

    talos_nodes = [n for n in spec.nodes if n.os_variant == "talos"]
    if not talos_nodes:
        print("[talos-config] No nodes declared with os_variant: talos in k3s-cluster.yaml")
        print("[talos-config] Set os_variant: talos on a server_nodes or worker_nodes entry to activate.")

    os.makedirs(output_dir, exist_ok=True)

    generate_installer_template(output_dir)

    used_talosctl = False
    if genconfig:
        used_talosctl = run_talosctl_genconfig(spec, output_dir)
        if not used_talosctl:
            print("[talos-config] talosctl not available — generating structural stubs only")

    if not used_talosctl:
        generate_base_controlplane(spec, output_dir)
        generate_base_worker(spec, output_dir)
        generate_talosconfig_stub(spec, output_dir)

    for node in talos_nodes:
        generate_node_patch(node, output_dir)

    write_readme(spec, output_dir, used_talosctl)

    return spec


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate Talos machine configs from k3s-cluster.yaml and bootstrap-state.json"
    )
    parser.add_argument("--state",     default="proxmox-bootstrap/bootstrap-state.json",
                        help="Path to bootstrap-state.json")
    parser.add_argument("--k3s",       default="proxmox-bootstrap/metadata/k3s-cluster.yaml",
                        help="Path to k3s-cluster.yaml")
    parser.add_argument("--output",    default="talos-configs",
                        help="Output directory for generated configs")
    parser.add_argument("--genconfig", action="store_true",
                        help="Call talosctl gen config to fill secrets (requires talosctl installed)")
    args = parser.parse_args(argv)

    spec = generate_talos_configs(
        state_path=args.state,
        k3s_path=args.k3s,
        output_dir=args.output,
        genconfig=args.genconfig,
    )

    talos_count = sum(1 for n in spec.nodes if n.os_variant == "talos")
    print(f"[talos-config] Done. {talos_count} Talos node(s) configured in {args.output}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
