#!/usr/bin/env python3
"""
Network-config snippet generator.

Reads bootstrap-state.json and generates a Cloud-Init network-config snippet
for each VM declared in the manifest. All network values (gateway, subnet prefix,
nameservers, interface name) come from the network_topology section — never
hard-coded in the snippet files themselves.

Usage (from proxmox-bootstrap/ directory):
    python3 generate-network-configs.py
    python3 generate-network-configs.py --bootstrap path/to/bootstrap-state.json
    python3 generate-network-configs.py --dry-run

Re-run whenever any of the following change:
    - network_topology.gateway
    - network_topology.management_cidr
    - network_topology.nameservers
    - network_topology.interface_name
    - vm[].initial_ip  (any VM's IP)
    - dns_registry     (any hostname/IP change)

The generated files are committed to the repository and uploaded to Proxmox
snippet storage unchanged (after SSH key population in user-data files).
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def _prefix_from_cidr(cidr: str) -> str:
    """Extract prefix length from CIDR, e.g. '192.168.50.0/24' → '/24'."""
    if "/" not in cidr:
        raise ValueError(f"management_cidr must be in CIDR notation (e.g. 192.168.1.0/24), got: {cidr!r}")
    return "/" + cidr.split("/")[1]


def generate_network_config(
    vm_name: str,
    vmid: int,
    cell_id: str,
    ip: str,
    prefix: str,
    gateway: str,
    nameservers: list[str],
    search_domain: str | None,
    interface: str,
    generated_at: str,
) -> str:
    ns_lines = "\n".join(f"        - {ns}" for ns in nameservers)
    search_line = (
        f"\n      search:\n        - {search_domain}" if search_domain else ""
    )

    return f"""\
# network-config - {vm_name}
# GENERATED by generate-network-configs.py - DO NOT EDIT MANUALLY
# Re-run the generator if network_topology or VM IPs change.
#
# Source: bootstrap-state.json -> network_topology + vms[{vmid}].initial_ip
# Cell:      {cell_id}
# VM ID:     {vmid}
# Interface: {interface}
# Static IP: {ip}{prefix}
# Gateway:   {gateway}
# Generated: {generated_at}

version: 2
ethernets:
  {interface}:
    dhcp4: false
    dhcp6: false
    addresses:
      - {ip}{prefix}
    gateway4: {gateway}
    nameservers:
      addresses:
{ns_lines}{search_line}
"""


def run(bootstrap_path: Path, output_dir: Path, dry_run: bool = False) -> list[str]:
    """
    Generate network-config files from bootstrap-state.json.

    Returns list of written file paths (or would-write paths in dry-run mode).
    """
    with open(bootstrap_path) as f:
        state = json.load(f)

    cell_id = state["cell_id"]
    topo = state["network_topology"]
    prefix = _prefix_from_cidr(topo["management_cidr"])
    gateway = topo["gateway"]
    nameservers = topo["nameservers"]
    search_domain = topo.get("search_domain")
    interface = topo["interface_name"]
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    written = []
    for vm in state["vms"]:
        content = generate_network_config(
            vm_name=vm["name"],
            vmid=vm["vmid"],
            cell_id=cell_id,
            ip=vm["initial_ip"],
            prefix=prefix,
            gateway=gateway,
            nameservers=nameservers,
            search_domain=search_domain,
            interface=interface,
            generated_at=generated_at,
        )

        out_path = output_dir / f"{vm['name']}.yaml"
        if dry_run:
            print(f"[dry-run] Would write {out_path}")
            print(content)
            print("---")
        else:
            out_path.write_text(content, encoding="utf-8")
            print(f"  wrote  {out_path}")

        written.append(str(out_path))

    return written


def main() -> None:
    args = sys.argv[1:]
    dry_run = "--dry-run" in args
    args = [a for a in args if a != "--dry-run"]

    # Resolve bootstrap-state path
    if "--bootstrap" in args:
        idx = args.index("--bootstrap")
        bootstrap_path = Path(args[idx + 1]).resolve()
    else:
        # Default: bootstrap-state.json in the same directory as this script
        bootstrap_path = Path(__file__).parent / "bootstrap-state.json"
        if not bootstrap_path.exists():
            # Fallback for running from repo root during testing
            bootstrap_path = (
                Path(__file__).parent.parent
                / "tests" / "fixtures" / "bootstrap" / "bootstrap-state.json"
            )

    if not bootstrap_path.exists():
        print(f"Error: bootstrap-state.json not found at {bootstrap_path}", file=sys.stderr)
        print("Use --bootstrap <path> to specify the manifest location.", file=sys.stderr)
        sys.exit(1)

    output_dir = Path(__file__).parent / "snippets" / "network-config"
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Bootstrap state: {bootstrap_path}")
    print(f"Output dir:      {output_dir}")
    if dry_run:
        print("Mode:            dry-run (no files written)")
    print()

    written = run(bootstrap_path, output_dir, dry_run=dry_run)

    if not dry_run:
        print(f"\nGenerated {len(written)} network-config snippet(s).")
        print("Commit the updated snippets and upload them to Proxmox snippet storage.")
        print("See SNIPPET-UPLOAD.md for upload instructions.")


if __name__ == "__main__":
    main()
