#!/usr/bin/env python3
"""
setup_dnsmasq.py — dnsmasq config generator and installer (Phase 1.F.8b).

Generates /etc/dnsmasq.d/broodforge.conf from dns-registry.yaml.
Called during forge phase-03 (host config) and re-runnable after any
dns-registry.yaml update to reload the live DNS configuration.

Split-horizon behaviour:
  LAN clients using hatchery as DNS:  hostname.domain → LAN IP
  WAN clients using public DNS:       hostname.domain → WAN IP (operator manages)
  Same FQDN, same Headscale URL, same spawn package — works from both locations.

Provides:
  DnsmasqConfig      — structured config representation
  generate_dnsmasq_config()  — build config from network_topology + dns_registry
  render_dnsmasq_conf()      — render to /etc/dnsmasq.d/broodforge.conf text
  validate_dnsmasq_config()  — check for obvious errors before writing
  config_to_dict()           — serialise for testing

Stdlib only.
"""

from dataclasses import dataclass, field
from typing import Optional


# ---------------------------------------------------------------------------
# DnsmasqConfig
# ---------------------------------------------------------------------------

@dataclass
class DnsmasqConfig:
    """Structured representation of the broodforge dnsmasq configuration."""

    # Bind address — hatchery LAN IP (None = bind all interfaces)
    listen_address:     Optional[str] = None

    # The operator's domain (home.example.com)
    domain:             str = "home.example.com"

    # Upstream resolvers (fallback for external names)
    upstream_servers:   list[str] = field(default_factory=lambda: ["8.8.8.8", "1.1.1.1"])

    # Address entries: list of (fqdn, ip) tuples
    address_entries:    list[tuple[str, str]] = field(default_factory=list)

    # Optional: hatchery FQDN (used to ensure hatchery itself is resolvable)
    hatchery_fqdn:      Optional[str] = None
    hatchery_lan_ip:    Optional[str] = None

    # Network profile (lan | wan) — affects split-horizon comment
    network_profile:    str = "lan"


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

def generate_dnsmasq_config(
    network_topology: dict,
    dns_registry:     list,
) -> DnsmasqConfig:
    """
    Build a DnsmasqConfig from network_topology dict and dns_registry list.

    network_topology keys used:
      management_cidr, gateway, profile
      wan_config.domain, wan_config.headscale_url

    dns_registry entries:
      [{id, name, fqdn, ip, type, ...}]
    """
    profile      = network_topology.get("profile") or "lan"
    domain       = (
        network_topology.get("wan_config", {}).get("domain")
        or network_topology.get("domain")
        or "home.example.com"
    )

    # Derive listen address from management CIDR gateway
    # (hatchery LAN IP is the gateway minus 1 subnet slot, or use first host)
    listen_address = None
    gateway = network_topology.get("gateway") or ""

    # Find hatchery entry in dns_registry (role=proxmox-host or name=hatchery)
    hatchery_fqdn   = None
    hatchery_lan_ip = None

    address_entries: list[tuple[str, str]] = []
    for entry in (dns_registry or []):
        # dns-registry.yaml entries use `hostname`; older callers used `fqdn`.
        fqdn = entry.get("fqdn") or entry.get("hostname") or ""
        ip   = entry.get("ip")   or entry.get("lan_ip") or ""
        if not (fqdn and ip):
            continue
        address_entries.append((fqdn, ip))
        role = entry.get("type") or entry.get("role") or ""
        if role == "proxmox-host" or entry.get("name") == "hatchery":
            hatchery_fqdn   = fqdn
            hatchery_lan_ip = ip
            listen_address  = ip

    return DnsmasqConfig(
        listen_address=listen_address,
        domain=domain,
        upstream_servers=["8.8.8.8", "1.1.1.1"],
        address_entries=address_entries,
        hatchery_fqdn=hatchery_fqdn,
        hatchery_lan_ip=hatchery_lan_ip,
        network_profile=profile,
    )


# ---------------------------------------------------------------------------
# Renderer
# ---------------------------------------------------------------------------

def render_dnsmasq_conf(config: DnsmasqConfig) -> str:
    """
    Render DnsmasqConfig to the text content of /etc/dnsmasq.d/broodforge.conf.

    Output is idempotent — re-running with the same config produces the same file.
    """
    lines: list[str] = []

    lines.append("# broodforge dnsmasq configuration")
    lines.append("# Generated by proxmox-bootstrap/setup_dnsmasq.py")
    lines.append("# Re-run after any dns-registry.yaml update.")
    lines.append("")

    if config.network_profile == "wan":
        lines.append("# Split-horizon DNS: LAN clients see LAN IPs; WAN clients")
        lines.append("# see WAN IPs via public DNS (operator-managed A record).")
        lines.append("# Same FQDN resolves correctly from both sides.")
    else:
        lines.append("# LAN-only DNS: all names resolve to LAN IPs.")
    lines.append("")

    # Bind address
    if config.listen_address:
        lines.append(f"listen-address={config.listen_address}")
    lines.append("bind-interfaces")
    lines.append("")

    # Domain
    lines.append(f"domain={config.domain}")
    lines.append("expand-hosts")
    lines.append("")

    # Upstream servers
    for srv in config.upstream_servers:
        lines.append(f"server={srv}")
    lines.append("")

    # Local address entries
    if config.address_entries:
        lines.append("# Local name → IP mappings (from dns-registry.yaml)")
        for fqdn, ip in sorted(config.address_entries):
            lines.append(f"address=/{fqdn}/{ip}")
        lines.append("")

    # No negative caching for local domain
    lines.append(f"local=/{config.domain}/")
    lines.append("")

    # Prevent forwarding of local names to upstream
    lines.append("bogus-priv")
    lines.append("no-resolv")
    lines.append("# Note: use server= entries above for upstream DNS")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Validator
# ---------------------------------------------------------------------------

@dataclass
class DnsmasqValidationError:
    field:   str
    message: str


def validate_dnsmasq_config(config: DnsmasqConfig) -> list[DnsmasqValidationError]:
    """
    Validate a DnsmasqConfig before writing it.

    Returns a list of errors. Empty list = configuration is valid.
    """
    errors: list[DnsmasqValidationError] = []

    if not config.domain:
        errors.append(DnsmasqValidationError("domain", "Domain cannot be empty"))

    if not config.upstream_servers:
        errors.append(DnsmasqValidationError("upstream_servers", "At least one upstream DNS server required"))

    if config.listen_address:
        parts = config.listen_address.split(".")
        if len(parts) != 4 or not all(p.isdigit() and 0 <= int(p) <= 255 for p in parts):
            errors.append(DnsmasqValidationError(
                "listen_address",
                f"listen_address {config.listen_address!r} is not a valid IPv4 address"
            ))

    # Check for duplicate FQDNs
    seen_fqdns: set[str] = set()
    for fqdn, ip in config.address_entries:
        if fqdn in seen_fqdns:
            errors.append(DnsmasqValidationError(
                "address_entries",
                f"Duplicate FQDN {fqdn!r} in address entries"
            ))
        seen_fqdns.add(fqdn)

    # Validate IP format for each entry
    for fqdn, ip in config.address_entries:
        parts = ip.split(".")
        if len(parts) != 4 or not all(p.isdigit() and 0 <= int(p) <= 255 for p in parts):
            errors.append(DnsmasqValidationError(
                "address_entries",
                f"Invalid IP {ip!r} for FQDN {fqdn!r}"
            ))

    return errors


# ---------------------------------------------------------------------------
# Serialisation helper
# ---------------------------------------------------------------------------

def config_to_dict(config: DnsmasqConfig) -> dict:
    """Serialise DnsmasqConfig to a plain dict (for logging/testing)."""
    return {
        "listen_address":   config.listen_address,
        "domain":           config.domain,
        "upstream_servers": list(config.upstream_servers),
        "address_count":    len(config.address_entries),
        "address_entries":  [(f, i) for f, i in config.address_entries],
        "hatchery_fqdn":    config.hatchery_fqdn,
        "hatchery_lan_ip":  config.hatchery_lan_ip,
        "network_profile":  config.network_profile,
    }


# ---------------------------------------------------------------------------
# CLI — used by forge phase-03 (host config). Generates the dnsmasq config from
# the manifest's network_topology + dns-registry.yaml.
# ---------------------------------------------------------------------------

def _read_dns_registry(path):
    """Read dns_registry list from a YAML (PyYAML if present) or JSON file."""
    import json as _json
    import sys as _sys
    text = open(path, encoding="utf-8").read()
    try:
        import yaml  # type: ignore
        data = yaml.safe_load(text)
    except Exception:
        try:
            data = _json.loads(text)
        except Exception:
            print(f"[setup-dnsmasq] WARNING: could not parse {path} (need PyYAML for "
                  f"YAML) — proceeding with an empty registry.", file=_sys.stderr)
            return []
    if isinstance(data, dict):
        return data.get("dns_registry") or []
    return data or []


def _cli_main() -> None:
    import argparse
    import json
    import os
    import sys

    ap = argparse.ArgumentParser(description="Generate the dnsmasq config for the hatchery.")
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--manifest", help="forge-manifest.json (or bootstrap-state.json)")
    src.add_argument("--state", help="bootstrap-state.json (alias of --manifest)")
    ap.add_argument("--dns-registry", dest="dns_registry",
                    help="Path to dns-registry.yaml (else read from the manifest)")
    ap.add_argument("--output", default="/etc/dnsmasq.d/broodforge.conf",
                    help="Output path (default: /etc/dnsmasq.d/broodforge.conf)")
    args = ap.parse_args()

    path = args.manifest or args.state
    with open(path, encoding="utf-8") as f:
        doc = json.load(f)
    nt = doc.get("network_topology") or {}

    if args.dns_registry and os.path.exists(args.dns_registry):
        registry = _read_dns_registry(args.dns_registry)
    else:
        registry = nt.get("dns_registry") or doc.get("dns_registry") or []

    config = generate_dnsmasq_config(nt, registry)
    conf = render_dnsmasq_conf(config)

    out = args.output
    parent = os.path.dirname(out)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(conf)
    print(f"[setup-dnsmasq] wrote {out} "
          f"({len(config.address_entries)} host mappings, domain {config.domain!r})")


if __name__ == "__main__":
    _cli_main()
