#!/usr/bin/env python3
"""
setup_headscale.py — Headscale auto-configuration generator (Phase 1.F.8a).

Generates Headscale config file and systemd unit content for the hatchery's
own tailnet coordinator. Called during forge phase-03 (host config).

The hatchery becomes the first node on its own tailnet. Spawn packages in WAN
mode embed a one-time Headscale auth key so broodlings can join the tailnet.

Provides:
  HeadscaleConfig           — structured config
  generate_headscale_config() — build from network_topology + host_identity
  render_headscale_yaml()    — render to /etc/headscale/config.yaml text
  render_headscale_unit()    — render systemd service unit
  headscale_init_commands()  — list of shell commands to initialise Headscale
  config_to_dict()           — serialise for testing

Stdlib only.
"""

from dataclasses import dataclass, field
from typing import Optional


# ---------------------------------------------------------------------------
# HeadscaleConfig
# ---------------------------------------------------------------------------

@dataclass
class HeadscaleConfig:
    """Structured representation of the Headscale configuration."""

    # Public-facing server URL (used by clients to register)
    server_url:         str = "https://localhost:8080"

    # Listen address for the Headscale gRPC + HTTP server
    listen_addr:        str = "0.0.0.0:8080"

    # gRPC listen address (for headscale CLI)
    grpc_listen_addr:   str = "127.0.0.1:50443"

    # Path to the SQLite database
    db_path:            str = "/var/lib/headscale/db.sqlite"

    # TLS config (set after cert issuance in phase-03)
    tls_cert_path:      Optional[str] = None
    tls_key_path:       Optional[str] = None

    # IP prefix for the tailnet (Tailscale default CGNAT range)
    ip_prefixes:        list[str] = field(default_factory=lambda: ["100.64.0.0/10"])

    # Log level
    log_level:          str = "info"

    # Broodforge namespace/user (created after Headscale starts)
    broodforge_user:    str = "broodforge"

    # OIDC disabled for homelab use
    oidc_disabled:      bool = True

    # DNS config for the tailnet
    dns_base_domain:    str = "brood.internal"


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

def generate_headscale_config(
    network_topology: dict,
    host_identity:    dict,
) -> HeadscaleConfig:
    """
    Build HeadscaleConfig from network_topology and host_identity dicts.

    Uses:
      host_identity.fqdn  → server_url base
      network_topology.wan_config.headscale_url (if present, takes precedence)
      network_topology.profile → tls_cert_path selection
    """
    fqdn    = host_identity.get("fqdn") or "hatchery.home.example.com"
    profile = network_topology.get("profile") or "lan"

    # Prefer explicit headscale_url from wan_config
    wan     = network_topology.get("wan_config") or {}
    server_url = wan.get("headscale_url") or f"https://{fqdn}:8080"

    # TLS paths depend on the TLS provider selected in 1.F.8d
    # Default to None (self-signed / configured later)
    tls_cert = network_topology.get("ssl_cert_path") or None
    tls_key  = network_topology.get("ssl_key_path")  or None

    # dns_base_domain derived from operator domain
    domain   = host_identity.get("domain") or "home.example.com"
    # Strip TLD for short internal domain
    parts = domain.split(".")
    dns_base = f"brood.{parts[-1]}" if len(parts) >= 2 else "brood.internal"

    return HeadscaleConfig(
        server_url=server_url,
        listen_addr="0.0.0.0:8080",
        grpc_listen_addr="127.0.0.1:50443",
        db_path="/var/lib/headscale/db.sqlite",
        tls_cert_path=tls_cert,
        tls_key_path=tls_key,
        log_level="info",
        broodforge_user="broodforge",
        dns_base_domain=dns_base,
    )


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------

def render_headscale_yaml(config: HeadscaleConfig) -> str:
    """
    Render HeadscaleConfig to /etc/headscale/config.yaml text.
    Minimal but complete for homelab use.
    """
    tls_block = ""
    if config.tls_cert_path and config.tls_key_path:
        tls_block = (
            f"\ntls_cert_path: {config.tls_cert_path}"
            f"\ntls_key_path: {config.tls_key_path}"
        )
    else:
        tls_block = "\n# tls_cert_path and tls_key_path will be set after cert issuance (phase-03)"

    prefixes = "\n".join(f"  - {p}" for p in config.ip_prefixes)

    return f"""\
# Headscale configuration — generated by broodforge setup_headscale.py
# Re-run setup_headscale.py after updating network_topology or TLS certs.

server_url: {config.server_url}
listen_addr: {config.listen_addr}
grpc_listen_addr: {config.grpc_listen_addr}
{tls_block.strip()}

db_type: sqlite3
db_path: {config.db_path}

ip_prefixes:
{prefixes}

log:
  level: {config.log_level}

dns_config:
  base_domain: {config.dns_base_domain}
  nameservers:
    - 1.1.1.1
    - 8.8.8.8
  magic_dns: true

oidc:
  # OIDC disabled — homelab use with API key authentication
  issuer: ""

ephemeral_node_inactivity_timeout: 30m
node_update_check_interval: 10s
"""


def render_headscale_unit() -> str:
    """Render the headscale systemd service unit file."""
    return """\
[Unit]
Description=Headscale — self-hosted Tailscale coordination server
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=headscale
Group=headscale
ExecStart=/usr/bin/headscale serve
Restart=on-failure
RestartSec=5s
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
"""


def headscale_init_commands(config: HeadscaleConfig) -> list[str]:
    """
    Return the ordered list of shell commands to initialise Headscale after install.

    These are run in forge phase-03 after the headscale package is installed and
    the config file is written.
    """
    return [
        # Create headscale system user/group if not exists
        "id headscale 2>/dev/null || useradd --system --no-create-home --shell /usr/sbin/nologin headscale",
        # Ensure data directory exists
        "install -d -m 750 -o headscale -g headscale /var/lib/headscale",
        # Enable and start Headscale
        "systemctl daemon-reload",
        "systemctl enable headscale",
        "systemctl start headscale",
        # Wait for Headscale to be ready
        "sleep 3",
        # Create the broodforge user namespace
        f"headscale users create {config.broodforge_user} 2>/dev/null || true",
        # Register the hatchery's own Tailscale with its Headscale
        # (operator must run: tailscale up --login-server <server_url>)
        f"echo '[headscale] Run on hatchery: tailscale up --login-server {config.server_url}'",
        # Generate an API key for spawn-planner.py to use
        "headscale apikeys create --expiration 8760h",
    ]


# ---------------------------------------------------------------------------
# Serialisation helper
# ---------------------------------------------------------------------------

def config_to_dict(config: HeadscaleConfig) -> dict:
    """Serialise HeadscaleConfig to a plain dict."""
    return {
        "server_url":       config.server_url,
        "listen_addr":      config.listen_addr,
        "grpc_listen_addr": config.grpc_listen_addr,
        "db_path":          config.db_path,
        "tls_cert_path":    config.tls_cert_path,
        "tls_key_path":     config.tls_key_path,
        "ip_prefixes":      list(config.ip_prefixes),
        "log_level":        config.log_level,
        "broodforge_user":  config.broodforge_user,
        "dns_base_domain":  config.dns_base_domain,
        "oidc_disabled":    config.oidc_disabled,
    }


# ---------------------------------------------------------------------------
# CLI — used by forge phase-03 (WAN profile). Writes the Headscale config.yaml +
# systemd unit; with --run, prints the init commands to execute on the host.
# ---------------------------------------------------------------------------

def _cli_main() -> None:
    import argparse
    import json
    import os
    import sys

    ap = argparse.ArgumentParser(description="Generate the Headscale coordinator config.")
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--manifest", help="forge-manifest.json (or bootstrap-state.json)")
    src.add_argument("--state", help="bootstrap-state.json (alias of --manifest)")
    ap.add_argument("--output-dir", default="/etc/headscale",
                    help="Where to write config.yaml (default: /etc/headscale)")
    ap.add_argument("--unit-dir", default="/etc/systemd/system",
                    help="Where to write the systemd unit (default: /etc/systemd/system)")
    ap.add_argument("--run", action="store_true",
                    help="Print the headscale init commands to execute on the host")
    args = ap.parse_args()

    path = args.manifest or args.state
    with open(path, encoding="utf-8") as f:
        doc = json.load(f)
    nt = doc.get("network_topology") or {}
    hi = doc.get("host_identity") or {}

    config = generate_headscale_config(nt, hi)

    os.makedirs(args.output_dir, exist_ok=True)
    cfg_path = os.path.join(args.output_dir, "config.yaml")
    with open(cfg_path, "w", encoding="utf-8") as f:
        f.write(render_headscale_yaml(config))
    print(f"[setup-headscale] wrote {cfg_path} (server_url {config.server_url})")

    try:
        os.makedirs(args.unit_dir, exist_ok=True)
        unit_path = os.path.join(args.unit_dir, "headscale.service")
        with open(unit_path, "w", encoding="utf-8") as f:
            f.write(render_headscale_unit())
        print(f"[setup-headscale] wrote {unit_path}")
    except OSError as exc:
        print(f"[setup-headscale] note: could not write systemd unit ({exc}).", file=sys.stderr)

    if args.run:
        print("[setup-headscale] run these on the host to finish setup:")
        for cmd in headscale_init_commands(config):
            print(f"    {cmd}")


if __name__ == "__main__":
    _cli_main()
