#!/usr/bin/env python3
"""
spawn_iac_generator.py — Spawn IaC and configuration generator (Phase 12.E.5).

Takes a spawn-plan.json dict and generates all deployment artifacts needed by
the spawn package:
  - OpenTofu .auto.tfvars (Proxmox VM declarations)
  - Cloud-Init user-data and network-config snippets (per VM)
  - Ansible inventory additions (broodling appended to existing groups)
  - Ansible k3s role vars (join token, server URL)

All generators return strings (no file I/O); callers write to disk.
write_all_artifacts() is the convenience function that writes everything.

Stdlib only.
"""

import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Spawn plan accessors
# ---------------------------------------------------------------------------

def _get(d, *keys, default=""):
    obj = d
    for k in keys:
        if not isinstance(obj, dict):
            return default
        obj = obj.get(k, default)
    return obj if obj is not None else default


def _ts(plan: dict) -> str:
    return plan.get("generated_at", datetime.now(timezone.utc).isoformat())


def _header(plan: dict, filename: str) -> str:
    return (
        f"# Generated by broodforge spawn_iac_generator.py\n"
        f"# Package: {plan.get('package_id', '?')}\n"
        f"# Broodling: {plan.get('hostname', '?')}\n"
        f"# Generated: {_ts(plan)}\n"
        f"# File: {filename}\n"
        f"# DO NOT EDIT — regenerate from spawn-plan.json\n\n"
    )


# ---------------------------------------------------------------------------
# 1. OpenTofu .auto.tfvars
# ---------------------------------------------------------------------------

def generate_tfvars(plan: dict) -> str:
    """
    Generate a Proxmox provider .auto.tfvars file for the spawn plan's VM set.
    The tfvars use broodling-specific VMIDs, IPs, bridge, and datastore names.
    """
    hostname      = plan.get("hostname", "unknown")
    hatchery_fqdn = _get(plan, "hatchery", "proxmox_cluster_address") or \
                    _get(plan, "hatchery", "fqdn", default="hatchery.internal")
    storage       = plan.get("storage") or {}
    network       = plan.get("network") or {}
    vms           = plan.get("vms") or []
    datastore     = storage.get("datastore_name", "local-zfs")
    bridge        = network.get("bridge", "vmbr0")

    lines = [
        _header(plan, f"spawn-{hostname}.auto.tfvars"),
        f'# Proxmox connection (uses hatchery credentials from KeePass)',
        f'proxmox_api_url      = "https://{hatchery_fqdn}:8006/api2/json"',
        f'proxmox_target_node  = "{hostname}"',
        f'',
        f'# VM declarations for broodling {hostname}',
        f'vms = {{',
    ]

    for vm in vms:
        vmid     = vm.get("vmid", "?")
        name     = vm.get("name", "?")
        template = vm.get("template_name", "ubuntu-2204-base")
        tmpl_id  = vm.get("template_id", 9000)
        cores    = vm.get("cores", 2)
        memory   = vm.get("memory_mb", 4096)
        disk_gb  = vm.get("disk_gb", 32)
        vm_bridge = vm.get("bridge", bridge)
        vm_ds    = vm.get("datastore", datastore)
        ip       = vm.get("ip", "")
        gw       = vm.get("gateway", network.get("gateway", ""))
        ci_user  = vm.get("initial_user", "ubuntu")

        lines += [
            f'  "{name}" = {{',
            f'    vmid          = {vmid}',
            f'    name          = "{name}"',
            f'    clone         = "{template}"',
            f'    clone_vmid    = {tmpl_id}',
            f'    cores         = {cores}',
            f'    memory        = {memory}',
            f'    disk_size     = "{disk_gb}G"',
            f'    storage       = "{vm_ds}"',
            f'    network_bridge = "{vm_bridge}"',
            f'    ip_config     = "ip={ip}/24,gw={gw}"',
            f'    ci_user       = "{ci_user}"',
            f'    agent_enabled = true',
            f'  }}',
        ]

    lines += ['}', '']
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# 2. Cloud-Init user-data (per VM)
# ---------------------------------------------------------------------------

def generate_cloudinit_user_data(vm: dict, plan: dict) -> str:
    """Generate a Cloud-Init user-data YAML snippet for one VM."""
    name      = vm.get("name", "vm")
    hostname  = vm.get("hostname") or name
    ci_user   = vm.get("initial_user", "ubuntu")
    packages  = vm.get("extra_packages") or []
    workspace = vm.get("workspace_path") or f"/opt/{name}"
    ssh_ref   = vm.get("ssh_key_reference", "")
    domain    = plan.get("domain", "internal")

    pkg_lines = "\n".join(f"  - {p}" for p in packages) if packages else ""
    pkg_section = f"packages:\n{pkg_lines}\n\n" if packages else ""

    return (
        f"# Cloud-Init user-data — {name}\n"
        f"# Auto-generated for spawn package: {plan.get('package_id', '?')}\n"
        f"#cloud-config\n\n"
        f"hostname: {hostname}\n"
        f"fqdn: {hostname}.{domain}\n"
        f"manage_etc_hosts: true\n\n"
        f"users:\n"
        f"  - name: {ci_user}\n"
        f"    groups: [sudo]\n"
        f"    shell: /bin/bash\n"
        f"    sudo: ALL=(ALL) NOPASSWD:ALL\n"
        f"    lock_passwd: false\n"
        f"    # SSH key injected by Proxmox from KeePass ref: {ssh_ref or '(none)'}\n\n"
        f"{pkg_section}"
        f"runcmd:\n"
        f"  - mkdir -p {workspace}\n"
        f"  - systemctl enable --now qemu-guest-agent\n\n"
        f"final_message: |\n"
        f"  Cloud-Init complete on {hostname}. Ready for Ansible.\n"
    )


# ---------------------------------------------------------------------------
# 3. Cloud-Init network-config (per VM)
# ---------------------------------------------------------------------------

def generate_cloudinit_network_config(vm: dict, plan: dict) -> str:
    """Generate a Cloud-Init network-config YAML snippet for one VM."""
    name      = vm.get("name", "vm")
    ip        = vm.get("ip", "")
    gateway   = vm.get("gateway") or _get(plan, "network", "gateway", default="")
    nameservers = _get(plan, "network", "nameservers", default=[]) or ["8.8.8.8"]
    ns_list   = ", ".join(f'"{n}"' for n in nameservers)
    interface  = "ens18"   # VirtIO NIC default in Proxmox

    return (
        f"# Cloud-Init network-config — {name}\n"
        f"# Auto-generated for spawn package: {plan.get('package_id', '?')}\n"
        f"version: 1\n"
        f"config:\n"
        f"  - type: physical\n"
        f"    name: {interface}\n"
        f"    subnets:\n"
        f"      - type: static\n"
        f"        address: {ip}\n"
        f"        netmask: 255.255.255.0\n"
        f"        gateway: {gateway}\n"
        f"        dns_nameservers: [{ns_list}]\n"
    )


# ---------------------------------------------------------------------------
# 4. Ansible inventory additions
# ---------------------------------------------------------------------------

def generate_ansible_inventory(plan: dict) -> str:
    """
    Generate an Ansible inventory INI section appending the broodling and
    its VMs to the relevant existing groups.
    """
    hostname = plan.get("hostname", "unknown")
    vms      = plan.get("vms") or []
    k3s_role = _get(plan, "k3s", "role", default="worker")
    domain   = plan.get("domain", "internal")

    lines = [
        _header(plan, f"inventory/spawn-{hostname}.ini"),
        f"# Broodling: {hostname}.{domain}",
        f"# Append this file to your existing Ansible inventory",
        f"",
        f"[proxmox_broodlings]",
        f"{hostname} ansible_host={plan.get('lan_ip', '')} "
        f"ansible_user=root",
        f"",
    ]

    # Group VMs by role
    role_groups: dict[str, list] = {}
    for vm in vms:
        role = vm.get("role", "unknown")
        role_groups.setdefault(role, []).append(vm)

    for role, vms_in_role in role_groups.items():
        # Convert role name to Ansible group (hyphens → underscores)
        group = role.replace("-", "_")
        lines.append(f"[{group}]")
        for vm in vms_in_role:
            name = vm.get("name", "?")
            ip   = vm.get("ip", "")
            ci_user = vm.get("initial_user", "ubuntu")
            lines.append(
                f"{name}.{domain} "
                f"ansible_host={ip} "
                f"ansible_user={ci_user} "
                f"proxmox_vmid={vm.get('vmid', '?')}"
            )
        lines.append("")

    # k3s group
    k3s_group = f"k3s_{k3s_role}"
    lines += [
        f"[{k3s_group}:children]",
    ]
    for role, vms_in_role in role_groups.items():
        if "k3s" in role.lower():
            lines.append(role.replace("-", "_"))
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# 5. Ansible k3s role vars (join token + server URL)
# ---------------------------------------------------------------------------

def generate_ansible_k3s_vars(plan: dict) -> str:
    """
    Generate Ansible group_vars YAML embedding the k3s join token and
    server URL from the spawn manifest.
    """
    k3s          = plan.get("k3s") or {}
    role         = k3s.get("role", "worker")
    server_url   = k3s.get("server_url", "")
    worker_token = k3s.get("worker_join_token") or "{{ vault_k3s_worker_token }}"
    server_token = k3s.get("server_join_token") or "{{ vault_k3s_server_token }}"
    token        = server_token if role == "server" else worker_token

    return (
        f"# Ansible k3s vars — {role} role\n"
        f"# Auto-generated for spawn package: {plan.get('package_id', '?')}\n"
        f"# Source: spawn-manifest.json k3s section\n\n"
        f"k3s_role: {role}\n"
        f"k3s_server_url: \"{server_url}\"\n"
        f"k3s_token: \"{token}\"\n"
        f"k3s_node_name: \"{plan.get('hostname', 'broodling')}\"\n"
    )


# ---------------------------------------------------------------------------
# 6. Convenience: write all artifacts to output directory
# ---------------------------------------------------------------------------

def write_all_artifacts(
    plan: dict,
    output_dir: Path,
    include_tfvars: bool = True,
    include_cloudinit: bool = True,
    include_ansible: bool = True,
) -> dict[str, Path]:
    """
    Write all generated artifacts to output_dir.
    Returns a dict mapping artifact type → Path of written file.
    """
    output_dir = Path(output_dir)
    written: dict[str, Path] = {}
    hostname = plan.get("hostname", "unknown")

    if include_tfvars:
        tf_path = output_dir / "opentofu" / f"spawn-{hostname}.auto.tfvars"
        tf_path.parent.mkdir(parents=True, exist_ok=True)
        tf_path.write_text(generate_tfvars(plan), encoding="utf-8")
        written["tfvars"] = tf_path

    if include_cloudinit:
        for vm in (plan.get("vms") or []):
            vm_name = vm.get("name", "vm")
            snippets_dir = output_dir / "cloud-init" / "snippets"
            ud_dir = snippets_dir / "user-data"
            nc_dir = snippets_dir / "network-config"
            ud_dir.mkdir(parents=True, exist_ok=True)
            nc_dir.mkdir(parents=True, exist_ok=True)

            ud_path = ud_dir / f"{vm_name}.yaml"
            nc_path = nc_dir / f"{vm_name}.yaml"
            ud_path.write_text(generate_cloudinit_user_data(vm, plan), encoding="utf-8")
            nc_path.write_text(generate_cloudinit_network_config(vm, plan), encoding="utf-8")
            written[f"user_data:{vm_name}"]    = ud_path
            written[f"network_config:{vm_name}"] = nc_path

    if include_ansible:
        inv_dir  = output_dir / "ansible"
        vars_dir = inv_dir / "group_vars"
        inv_dir.mkdir(parents=True, exist_ok=True)
        vars_dir.mkdir(parents=True, exist_ok=True)

        inv_path  = inv_dir / f"spawn-{hostname}.ini"
        vars_path = vars_dir / "k3s_all.yml"
        inv_path.write_text(generate_ansible_inventory(plan), encoding="utf-8")
        vars_path.write_text(generate_ansible_k3s_vars(plan), encoding="utf-8")
        written["ansible_inventory"] = inv_path
        written["ansible_k3s_vars"]  = vars_path

    return written
