#!/usr/bin/env bash
# sync-cert-to-k8s.sh — Sync TLS certificate into Kubernetes TLS secrets.
#
# Phase 1.F.8d (DuckDNS path): copies the acme.sh wildcard cert into k8s TLS
# secrets in each configured namespace. Called by acme.sh --reloadcmd and as a
# weekly k8s CronJob to catch cert renewal drift.
#
# CONFIGURATION — resolved in order:
#   1. Environment variables (CERT_PATH, KEY_PATH, SECRET_NAME, NAMESPACES)
#   2. /etc/broodforge/ssl-config  (key=value, one per line, written by setup_tls.py)
#   3. Built-in defaults (standard broodforge acme.sh cert paths)
#
# A site-specific version with cert paths hard-coded is generated by setup_tls.py
# (render_sync_cert_sh()) and deployed at hatchery forge time. This static version
# in the repo is the fallback for the remediation engine when the generated version
# is not yet in place.
#
# Exit codes:
#   0  — sync completed successfully
#   1  — hard error (kubectl failed, unexpected I/O error)
#   2  — NOT_IMPLEMENTED / not yet configured (cert not found, kubectl not available)
#        The remediation engine records this as a soft failure — expected before TLS
#        is set up on the hatchery.
#
# Usage:
#   bash sync-cert-to-k8s.sh
#   NAMESPACES="default monitoring" bash sync-cert-to-k8s.sh
#   CERT_PATH=/etc/letsencrypt/live/foo/fullchain.pem bash sync-cert-to-k8s.sh

set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults (match broodforge standard acme.sh install paths — see setup_tls.py)
# ---------------------------------------------------------------------------
_DEFAULT_CERT="/etc/broodforge/ssl/fullchain.pem"
_DEFAULT_KEY="/etc/broodforge/ssl/privkey.pem"
_DEFAULT_SECRET="broodforge-tls"
_DEFAULT_NAMESPACES="default"

# ---------------------------------------------------------------------------
# Load /etc/broodforge/ssl-config if present (generated by setup_tls.py)
# ---------------------------------------------------------------------------
_CONFIG_FILE="/etc/broodforge/ssl-config"
if [ -f "$_CONFIG_FILE" ]; then
    # shellcheck source=/dev/null
    while IFS='=' read -r _k _v; do
        case "$_k" in
            CERT_PATH)    export CERT_PATH="${CERT_PATH:-$_v}" ;;
            KEY_PATH)     export KEY_PATH="${KEY_PATH:-$_v}" ;;
            SECRET_NAME)  export SECRET_NAME="${SECRET_NAME:-$_v}" ;;
            NAMESPACES)   export NAMESPACES="${NAMESPACES:-$_v}" ;;
        esac
    done < "$_CONFIG_FILE"
fi

CERT_PATH="${CERT_PATH:-$_DEFAULT_CERT}"
KEY_PATH="${KEY_PATH:-$_DEFAULT_KEY}"
SECRET_NAME="${SECRET_NAME:-$_DEFAULT_SECRET}"
NAMESPACES="${NAMESPACES:-$_DEFAULT_NAMESPACES}"

# ---------------------------------------------------------------------------
# Pre-flight checks — exit 2 for NOT_IMPLEMENTED / not configured
# ---------------------------------------------------------------------------

if ! command -v kubectl &>/dev/null; then
    echo "[sync-cert-to-k8s] FORGE_INCOMPLETE: kubectl not found in PATH." >&2
    echo "[sync-cert-to-k8s]   k3s is not yet installed or kubectl is not on PATH." >&2
    echo "[sync-cert-to-k8s]   This action will succeed once the hatchery k3s cluster is running." >&2
    exit 2
fi

if [ ! -f "$CERT_PATH" ]; then
    echo "[sync-cert-to-k8s] FORGE_INCOMPLETE: certificate not found: $CERT_PATH" >&2
    echo "[sync-cert-to-k8s]   TLS is not yet configured on this hatchery." >&2
    echo "[sync-cert-to-k8s]   Run setup_tls.py (or forge phase-03) to issue a certificate," >&2
    echo "[sync-cert-to-k8s]   or set CERT_PATH to the correct fullchain.pem path." >&2
    exit 2
fi

if [ ! -f "$KEY_PATH" ]; then
    echo "[sync-cert-to-k8s] FORGE_INCOMPLETE: private key not found: $KEY_PATH" >&2
    echo "[sync-cert-to-k8s]   Set KEY_PATH to the correct privkey.pem path." >&2
    exit 2
fi

# ---------------------------------------------------------------------------
# Sync cert into each namespace
# ---------------------------------------------------------------------------

echo "[sync-cert-to-k8s] Syncing $CERT_PATH → k8s secret '$SECRET_NAME' ..."

_any_failed=0
for _ns in $NAMESPACES; do
    if kubectl create secret tls "$SECRET_NAME" \
        --cert="$CERT_PATH" \
        --key="$KEY_PATH" \
        --namespace="$_ns" \
        --dry-run=client -o yaml 2>/dev/null | kubectl apply -f - 2>&1; then
        echo "[sync-cert-to-k8s] Synced '$SECRET_NAME' to namespace '$_ns'"
    else
        echo "[sync-cert-to-k8s] ERROR: failed to sync '$SECRET_NAME' to namespace '$_ns'" >&2
        _any_failed=1
    fi
done

if [ "$_any_failed" -ne 0 ]; then
    echo "[sync-cert-to-k8s] One or more namespace syncs failed — check kubectl access and RBAC." >&2
    exit 1
fi

echo "[sync-cert-to-k8s] Certificate sync complete."
